### ISSUE TITLE
Add a Valid() function to check if a string is a valid color(ie parses)

### ISSUE THREAD

**Issue by epelc** [go-playground/colors#7]
Any thoughts on adding a `Valid(color string) bool` function to quickly check if a string is color? Perhaps with `ValidRGB, ValidHex, etc` siblings.

Would look something like this

```
func Valid(color string) bool {
  if _, err := Parse(color); err != nil{
    return false
  }
return true
}

```

**Comment by joeybloggs** [comment]
Hey @epeic

Ya I’m good with that as a convenience method, make a PR and I’ll get it merged.
