### ISSUE TITLE
Wrong standard library interface implementation

### ISSUE THREAD

**Issue by vanni-giachin** [go-playground/colors#9]
The `RGBA() (r, g, b, a uint32)` implementation is wrong because:

- the float64 `A` field (alpha channel in a [0-1] range) is truncated by a int32 cast
- the method should return four values in a 16-bits range, so [0-65535] (see [src/image/color/color.go](https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/image/color/color.go))

**Comment by vanni-giachin** [comment]
Solved by #10

**Comment by deankarn** [comment]
#10 merged
